# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
permit_join: true

# enable the web i/f on port 8080
frontend: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Setting for Sonoff Zigbee 3.0 USB Dongle
  port: /dev/ttyACM0
  adapter: ember
  rtscts: true

# Optional: advanced settings
advanced:
  # For inital work set log level to debug
  log_level: debug
  # Logging is handled by snap, do not log to file by default
  log_output:
    - console
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false

device_options:
  legacy: false
